services:

  traefik:
    image: traefik:v2.10

    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"

      - "--entrypoints.web.address=:8080"
      - "--entrypoints.traefik.address=:8081"

      # ✅ SOLO ESTA (NO directory)
      - "--providers.file=true"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
      - "--log.level=DEBUG"

    ports:
      - "8000:8080"
      - "8081:8081"

    volumes:
      - ${PWD}/dynamic.yml:/etc/traefik/dynamic.yml

    networks:
      - proxy

networks:
  proxy:
    external: true